baseurl = "http://ictgamejam.githumb.io/"
title = "ICT Game Jam"
languageCode = "en-us"
MetaDataFormat = "toml"
theme = "hyde-x"
paginate = 10
staticdir = "static"

[permalinks]
    post = "/blog/:year/:month/:day/:title/"

[taxonomies]
    category = "categories"
    tag = "tags"
    series = "series"


[params]
    truncate = true

    defaultDescription = "ICT Game Jam"
    defaultKeywords = "Wichita,ilovewichita,wichitawesome,gamedev,midwestgamedev,gamejam,devICT,MakeICT"

    hideReadingTime = true

    customCSS = ""

    home = "RSVP!"

    facebook = "https://www.facebook.com/developerict/"
    twitter = "https://twitter.com/ICTGameJam"
