# Site settings
baseurl = "http://devict.github.io/ictgamejam/"
languageCode = "en-us"
title = "ICT Game Jam"
# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[params]

name = "ICT Game Jam"
description = "Build a game at Wichita's biggest game development party!!"
author = "Jim Rice"
email = "ictgamejam@makeict.org"

custom_css = []
custom_js  = []

[[params.social]]
  icon = "fa-twitter"
  link = "https://twitter.com/ICTGameJam"
