# Site settings
baseurl = "http://devict.github.io/ictgamejam/"
languageCode = "en-us"
title = "ICT Game Jam"
theme = "hugo-agency-theme"
# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) or
	# most longer texts.
	#
	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "ICT Game Jam"
	description = "Build a game at Wichita's biggest game development party!!"
  author = "Jim Rice"

	# Since this template is static, the contact form uses www.formspree.io as a
	# proxy. The form makes a POST request to their servers to send the actual
	# email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
	email = "ictgamejam@makeict.org"

    # Link custom assets relative to /statuc
    custom_css = ["custom.css"]
    custom_js  = []


	# Navigation
	[params.navigation]
		brand = "February 3-5 2017"
		event = "Event"
		schedule = "Schedule"
		help = "Help!"
		services = "Services"
		portfolio = "Portfolio"
		about = "About"
		team = "Judges"
		contact = "Contact"

    # Add custom links. Those can be pre- and postpended to the default menu above.
    # Use the weight attribute to order your custom links. Uncomment the example
    # below and replace the values with your own.

    # prepended links
    #[[menu.prepend]]
    #    url = "http://gohugo.io"
    #    name = "Hugo"
    #    weight = 10

    # postpended links
    [[menu.postpend]]
        url = "https://www.eventbrite.com/e/wichita-esports-convention-tickets-28640291884#tickets"
        name = "RSVP!"
        weight = 10


	# Hero section
	[params.hero]
		# To change the background image of the hero, replace 'header-bg.jpg' in
		# the 'static/img' folder.
		# title = "Welcome To Our Studio!"
		# subtitle = "It's nice to meet you"
		buttonText = "What's a game jam?"


	# Event section
	[params.event]
    enable = true
		title = "It's a PARTY"
		subtitle = "Ok, **technically** it's a competition with cash prizes.  It's not a workshop or a class about making games.  But if you want to spend a weekend learning gamedev and getting fed, you'll be in good company.<br><br><a href=\"https://www.eventbrite.com/e/wichita-esports-convention-tickets-28640291884#tickets\" class=\"page-scroll btn btn-xl\">You should RSVP</a>"

        [[params.event.row]]

			[[params.event.row.list]]
				icon = "fa-gamepad"
				title = "Do I need to have made a game before?"
				description = "Plenty of previous participants had little or no gamedev experience, but they had a blast.  We'll have lots of people willing to answer questions and help you learn at your own pace!"

            [[params.event.row.list]]
                icon = "fa-code"
                title = "Do I need to be a programmer?"
                description = "No!  Games also need artists, writers, and designers.  There is no rule for whether your game must be 2D, 3D, complex, or even have graphics."

            [[params.event.row.list]]
                icon = "fa-laptop"
                title = "Do I need a computer?"
                description = "Computers cannot be provided for this event, however it's possible external monitors will be available at your desk space!"

			[[params.event.row.list]]
                icon = "fa-heart"
                title = "I love it! I must know more!"
                description = "If you insist!  The event is generously hosted at [WSU Experiential Engineering building](http://www.wichita.edu/thisis/stories/story.asp?si=3511) during the [Wichita eSports Expo](https://www.facebook.com/events/243882846026141/).  We will have snacks, drinks and T-shirt waiting for you!  Lunch and Dinner will be provided on Saturday, and lunch provided on Sunday.  All that's left is to [RSVP](https://www.eventbrite.com/e/wichita-esports-convention-tickets-28640291884#tickets) (choose a gamejam-specific ticket)  and follow [@ICTGameJam](https://twitter.com/ICTGameJam)!"


	# Schedule timeline
	[params.schedule]
	      enable = true
		title = "Schedule"
		subtitle = "Great!  Now that you're going to the game jam, here's how the weekend will go..."
		endpoint = "Keep<br>making<br>games!"

		# The events will be listed from the top to the bottom.
		# All images are stored under 'static/img/about'.
		# Replace them with your own.
		[[params.schedule.events]]
			img= "1.jpg"
			date = "Friday"
			title = "Kickoff!"
			description = "Doors open at 6pm, kickoff slides and intro start at 7pm.  Participants will receive an email to vote on the game jam's theme.  Those needing teams will have an opportunity to pitch ideas and form or join teams as necessary.  You can even work solo if you want.  Then it's time to start making games!  Doors close at 11pm.  You can continue working, but will need to leave the campus!"

		[[params.schedule.events]]
			img = "2.jpg"
			date = "Saturday"
			title = "Build Day!"
			description = "Show up at 10am.  Enjoy refreshments, 2 meals and ... oh yeah... build a game!  Hit a wall?  Ask for help!  Lean on the volunteers and fellow game devs for feedback and encouragement!  Doors close at 11pm.  You can continue working, but will need to leave the campus!"

		[[params.schedule.events]]
			img = "3.jpg"
			date = "Sunday"
			title = "Polish, SHIP IT!!  Community Play.  Winners announced!"
			description = "Arrive at 10am to put the finishing touches on your game.  Work stops, lunch begins at 12pm.  Judges play your games 1 - 2pm.  Doors open to the public 2 - 4pm to play your games and vote for Community Choice while the judges deliberate.  Winners announced at 5:30pm."

	# help section
	[params.help]
    enable = true
		title = "Help!"
		subtitle = "The best way to help is to [RSVP](https://www.eventbrite.com/e/wichita-esports-convention-tickets-28640291884#tickets) and participate!  Otherwise we welcome volunteered time or talent in any amount before, during or after the event.<br><br>Finally, if you absolutely insist, here are some sponsorship packages to consider!  For all these, please contact [ictgamejam@makeict.org](mailto:ictgamejam@makeict.org).<br><br>This and all devICT gamedev events are operated under MakeICT, a 501c3 organization.  All donations are used to run this and future gamedev events."

        [[params.help.row]]

            [[params.help.row.list]]
                icon = "fa-wrench"
                title = "Italian Plumber 1-1: $250"
                description = "<i class=\"fa fa-caret-right\"></i> Thanks via ICT Game Jam (Twitter), MakeICT and devICT (Twitter, Facebook), twice before event.<br><i class=\"fa fa-caret-right\"></i> Thanks at Friday kickoff presentation, and awards announcements on Sunday.<br><i class=\"fa fa-caret-right\"></i> Logo or name on 2017 event page."

            [[params.help.row.list]]
                icon = "fa-arrow-up"
                title = "Protein Mushroom: $500"
                description = "<i class=\"fa fa-caret-right\"></i> Everything from Italian Plumber 1-1 package.<br><i class=\"fa fa-caret-right\"></i> Display of provided promotional banner at event.<br><i class=\"fa fa-caret-right\"></i> Inclusion of any desired promotional items or material in participants’ swag packs."

            [[params.help.row.list]]
                icon = "fa-star"
                title = "Invincibility: $1500"
                description = "<i class=\"fa fa-caret-right\"></i> Everything in Protein Mushroom package.<br><i class=\"fa fa-caret-right\"></i> Table space at event for provided promotional material.<br><i class=\"fa fa-caret-right\"></i> Monthly thanks via social media through February 2018."

			[[params.help.row.list]]
                icon = "fa-car"
                title = "Blue Shell: $3000"
                description = "<i class=\"fa fa-caret-right\"></i> Everything in Invincibility package.<br><i class=\"fa fa-caret-right\"></i> Table, banner space, and sponsorship thanks at 2 devICT Gamedev Build or Demo Days.<br><i class=\"fa fa-caret-right\"></i> Logo or name displayed in all event videos."


	# Services section
	[params.services]
        enable = false
		title = "Services"
		subtitle = "Lorem ipsum dolor sit amet consectetur."

        [[params.services.row]]

            [[params.services.row.list]]
                icon = "fa-shopping-cart"
                title = "E-Commerce"
                description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."

            [[params.services.row.list]]
                icon = "fa-laptop"
                title = "Responsive Design"
                description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."

            [[params.services.row.list]]
                icon = "fa-lock"
                title = "Web"
                description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."

	# Portfolio section
	[params.portfolio]
        enable = false
		# All projects defined in their own files. You can find example projects
		# at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
		# at the root of this Hugo site.
		# For more informtion take a look at the README.
		title = "Portfolio"
		subtitle = "Lorem ipsum dolor sit amet consectetur."

		[params.portfolio.modal]
            client = "Client"
            date = "Date"
            category = "Category"
            buttonText = "Close project"


  # About section

	[params.about]
    enable = false
		title = "About"
		subtitle = "Lorem ipsum dolor sit amet consectetur."
		endpoint = "Be part<br>of our<br>story!"

		# The events will be listed from the top to the bottom.
		# All images are stored under 'static/img/about'.
		# Replace them with your own.
		[[params.about.events]]
			img = "1.jpg"
			date = "2009-2011"
			title = "Our Humble Beginnings"
			description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"

		[[params.about.events]]
			img = "2.jpg"
			date = "March 2011"
			title = "An Agency is Born"
			description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"

		[[params.about.events]]
			img = "3.jpg"
			date = "December 2012"
			title = "Our Humble Beginnings"
			description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"

		[[params.about.events]]
			img = "4.jpg"
			date = "July 2014"
			title = "Phase Two Expansion"
			description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"


	# Team section
	[params.team]
    enable = true
		title = "Our fearless judges"
		subtitle = "From near AND distant lands!"

		# All team member's pictures are stored under 'static/img/team'.
		# Replace them with your own too.
		[[params.team.members]]
			img = "2017-02-brent.jpg"
			name = "Brent Sodman"
			position = "<i class=\"fa fa-caret-right\"></i> Founder of [Dodge Roll Games](https://twitter.com/dodgerollgames).<br><i class=\"fa fa-caret-right\"></i> Programmer of [Enter the Gungeon](http://dodgeroll.com/gungeon/), released April 2016.<br><i class=\"fa fa-caret-right\"></i> Former technical artist at Electronic Arts.<br><i class=\"fa fa-caret-right\"></i> The best type of jam is game jam."
			social = [
				["fa-twitter", "https://twitter.com/DodgeRollBrent"],
                ["fa-envelope", "mailto:brent@dodgeroll.com"]
			]

		# All team member's pictures are stored under 'static/img/team'.
		# Replace them with your own too.
		[[params.team.members]]
			img = "2017-02-sophii.jpg"
			name = "Sophii!"
			position = "<i class=\"fa fa-caret-right\"></i> Fancies herself a Smite Overlord, wins 'some' matches.<br><i class=\"fa fa-caret-right\"></i> Recreates and wears the skin of her enemies, calls it Cosplay.<br><i class=\"fa fa-caret-right\"></i> Will work for Full Throttle Energy Drink."
			social = [
				["fa-twitter", "https://twitter.com/UltraGirlsCos"],
                ["fa-facebook", "https://www.facebook.com/OhMySophii"],
                ["fa-instagram", "https://www.instagram.com/ohmysophii/"]
			]


	# Client section
    [params.clients_list]
        enable = true
				title = "Our amazing sponsors"
				subtitle = "Thanks for making this event possible!!"

    	# All the clients' logos are stored under 'static/img/logos'.
    	# Replace them with your clients's logos.
    	[[params.clients]]
    		logo = "devict_logo_260.png"
    		link = "http://devict.org"

    	[[params.clients]]
    		logo = "MakeICT-260.png"
    		link = "http://makeict.org"

    	[[params.clients]]
    		logo = "Storehouse-Logo-260.png"
    		link = "https://sthse.co/"

		[[params.clients]]
			logo = "callcap_logo_260.png"
			link = "https://www.callcap.com/"

		[[params.clients]]
			logo = "Roll20-260.png"
			link = "https://roll20.net/"

		[[params.clients]]
			logo = "carlos-260.png"
			link = "https://www.carlosokellys.com/"

		[[params.clients]]
			logo = "bnm-logo.png"
			link = "http://www.barrettmorgandesignllc.com/"

		[[params.clients]]
			logo = "fireshark-truck-emblem-260.png"
			link = "https://www.fireshark.com/"

		[[params.clients]]
			logo = "labor-party-260.png"
			link = "http://labor-party.com/"

		[[params.clients]]
			logo = "bcw_icon-260.png"
			link = "http://bullercodeworks.com/"

	# Contact section
	[params.contact]
    enable = false
		title = "Contact us"
		subtitle  = "Lorem ipsum dolor sit amet consectetur."
		buttonText = "Send message"

		# 'warning' defines error messages for invalid inputs
		[params.contact.form.name]
			text = "Your Name *"
			warning = "Please enter your name."

		[params.contact.form.email]
			text = "Your Email *"
			warning = "Please enter your email address."

		[params.contact.form.phone]
			text = "Your Phone *"
			warning = "Please enter your phone number."

		[params.contact.form.message]
			text = "Your Message *"
			warning = "Please enter a message."


	# Footer section
	[params.footer]
        enable = true
		copyright = "Published under the Apache License 2.0."

		[[params.footer.social]]
			icon = "fa-twitter"
			link = "https://twitter.com/ICTGameJam"

		[[params.footer.social]]
			icon = "fa-facebook"
			link = "https://www.facebook.com/events/263285980716220/"

		[[params.footer.quicklinks]]
			text = "devICT"
			link = "http://devict.org/"

		[[params.footer.quicklinks]]
			text = "Email ICT Game Jam"
			link = "mailto:ictgamejam@makeict.org"
